import type { LucideIcon } from "lucide-react";
import {
  Accessibility,
  Atom,
  BookOpen,
  Bot,
  Clock,
  Database,
  FileText,
  FlaskConical,
  LayoutGrid,
  Megaphone,
  Palette,
  Plug,
  Shield,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Triangle,
  Workflow,
} from "lucide-react";

const exactIcons: Record<string, LucideIcon> = {
  all: LayoutGrid,
  todas: LayoutGrid,
  todos: LayoutGrid,
  recent: Clock,
  popular: TrendingUp,
  skill: Sparkles,
  skills: Sparkles,
  agent: Bot,
  agents: Bot,
  mcp: Plug,
  mcps: Plug,
  doc: FileText,
  docs: FileText,
  accessibility: Accessibility,
  "agent-workflows": Workflow,
  cybersecurity: Shield,
  databases: Database,
  "design-ui": Palette,
  documentation: BookOpen,
  "frontend-react": Atom,
  "mcp-integrations": Plug,
  marketing: Megaphone,
  mobile: Smartphone,
  nextjs: Triangle,
  testing: FlaskConical,
  performance: TrendingUp,
  composition: LayoutGrid,
  typescript: FileText,
  tailwind: Palette,
  shadcn: Palette,
  "app-router": Triangle,
  "server-components": Atom,
  caching: Database,
  deployment: Plug,
  critique: Palette,
  "design-tokens": Palette,
  components: LayoutGrid,
  animation: Sparkles,
  expo: Smartphone,
  "react-native": Smartphone,
  ios: Smartphone,
  android: Smartphone,
  planning: Workflow,
  debugging: Bot,
  subagents: Bot,
  "autonomous-loops": Workflow,
  "skill-authoring": Sparkles,
  postgresql: Database,
  supabase: Database,
  prisma: Database,
  drizzle: Database,
  migrations: Database,
  neon: Database,
  convex: Database,
  tdd: FlaskConical,
  playwright: FlaskConical,
  e2e: FlaskConical,
  unit: FlaskConical,
  seo: Megaphone,
  copywriting: Megaphone,
  cro: Megaphone,
  growth: Megaphone,
  wcag: Accessibility,
  aria: Accessibility,
  owasp: Shield,
  auth: Shield,
  secrets: Shield,
  audits: Shield,
  filesystem: Plug,
  github: Plug,
  database: Database,
  search: Sparkles,
  deploy: Plug,
  frameworks: BookOpen,
  orm: Database,
  protocols: BookOpen,
};

const keywordIcons: Array<{ match: RegExp; icon: LucideIcon }> = [
  { match: /accessib|a11y|wcag|aria/, icon: Accessibility },
  { match: /secur|cyber|owasp|auth|secret|audit/, icon: Shield },
  { match: /database|postgres|prisma|sql|neon|supabase/, icon: Database },
  { match: /design|ui|token|palette|tailwind|shadcn/, icon: Palette },
  { match: /doc|book|guide|protocol/, icon: BookOpen },
  { match: /react|frontend|component|atom/, icon: Atom },
  { match: /mcp|plugin|integrat|github|deploy/, icon: Plug },
  { match: /market|seo|copy|growth/, icon: Megaphone },
  { match: /mobile|ios|android|expo/, icon: Smartphone },
  { match: /next/, icon: Triangle },
  { match: /test|tdd|e2e|playwright/, icon: FlaskConical },
  { match: /agent|workflow|bot/, icon: Workflow },
  { match: /skill/, icon: Sparkles },
];

export function getTaxonomyIcon(slugOrName?: string | null): LucideIcon {
  const key = slugOrName?.trim().toLowerCase() ?? "";
  if (!key) return Tag;
  const normalized = key.replace(/[\s_/]+/g, "-");
  if (exactIcons[normalized]) return exactIcons[normalized];
  if (exactIcons[key]) return exactIcons[key];
  const hit = keywordIcons.find((item) => item.match.test(normalized));
  return hit?.icon ?? Tag;
}
